apiVersion: v1
kind: Service
metadata:
  name: evolved-todo-{{ .Values.frontend.name }}
  labels:
    app: evolved-todo
    component: {{ .Values.frontend.name }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
  - port: {{ .Values.frontend.service.port }}
    targetPort: {{ .Values.frontend.service.targetPort }}
    protocol: TCP
    name: http
  selector:
    app: evolved-todo
    component: {{ .Values.frontend.name }}
