apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.name }}
  labels:
    {{- include "evolved-todo-ai-generated.labels" . | nindent 4 }}
    app: {{ .Values.backend.name }}
spec:
  selector:
    {{- include "evolved-todo-ai-generated.selectorLabels" . | nindent 4 }}
    app: {{ .Values.backend.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetPort }}
  type: {{ .Values.backend.service.type }}
