{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: todo-app-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: {{ .Values.ingress.paths.api.path }}
        pathType: {{ .Values.ingress.paths.api.pathType }}
        backend:
          service:
            name: {{ .Values.backend.name }}
            port:
              number: {{ .Values.backend.service.port }}
      - path: {{ .Values.ingress.paths.root.path }}
        pathType: {{ .Values.ingress.paths.root.pathType }}
        backend:
          service:
            name: {{ .Values.frontend.name }}
            port:
              number: {{ .Values.frontend.service.port }}
{{- end }}
