apiVersion: v1
kind: Service
metadata:
  name: todo-frontend
  namespace: default
  labels:
    app: todo-frontend
spec:
  type: ClusterIP
  selector:
    app: todo-frontend
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    protocol: TCP
